### PR TITLE
Fallback to default `Configuration` in `Client.new`

### LINKED ISSUE #74: Using `Client` directly breaks following README examples
Hey there! I'm just starting down the path of an ActiveCampaign integration working against HEAD where I'm using `ActiveCampaign:::Client.new` and found I needed to add a couple extra options vs. what's shown in the README (which suggests I only need to set `api_url` and `api_token`).

```
    ActiveCampaign::Client.new(
      api_url: api_url,
      api_token: api_token,
      response_middleware: {},
      adapter: :net_http,
    )
```

If I don't set `response_middlewhere` to empty hash, I get a nil error when invoking `#none?` on nil. And if I don't specify an `adapter`, faraday can't make requests (error is "wrong constant name"). 

Would you be open to a PR that either:

- updates the README to show these other keys?
- sets a default `adapter` value / gracefully handles a nil `response_middleware` value?

Which of these approaches would be preferred? Let me know and I'd be happy to open a PR.

Thanks!

### PR DESCRIPTION
**Pull request by rylwin**
Use `Configuration` to provide default option when using `Client.new` in
order to avoid `nil` errors that would occur when using `Client.new`
directly without the user specifying the `:adapter` and
`:response_middleware` options.

Fix #74

### CODE REVIEW

**Comment by rylwin** [comment]
@mhenrixon after looking through the code I saw I could use `Configuration` to populate default values for the config hash. Let me know what you think of this approach.

I also wasn't sure the best way to approach the test here -- I didn't want to rely on specific ActiveCampaign endpoints, so ended up mocking a fake request. Happy to change the approach if you'd like me to take a different direction.

Also, I don't think I increased the lint offense count, but let me know if I missed something and need to make a change there. 

Looking forward to your comments!

File: spec/lib/active_campaign/client_spec.rb [hunk 1]
```diff
@@ -0,0 +1,10 @@
+# frozen_string_literal: true
+
+RSpec.describe ActiveCampaign::Client, :vcr do
+  describe '.new' do
+    it 'can be used to intialize a client object that can make requests' do
+      WebMock.stub_request(:get, 'http://fake.com/').with(body: '{}')
+      described_class.new.get('http://fake.com/')
```
Comment (mhenrixon) [inline spec/lib/active_campaign/client_spec.rb:7]: That's a good smoke test, perhaps we could actually add an expectation as well? Just to make sure that we are not just relying on that an error is not raised? I also think the webmock stuff isnt' working.

Comment (rylwin) [reply spec/lib/active_campaign/client_spec.rb:8]: You're right -- great catch. The spec wasn't doing exactly what I thought it was. I think I've fixed the issue and also now explicitly check that the request is made. How does it look?

**Review by mhenrixon — APPROVED** [review]
I'll get this merged tomorrow morning

File: lib/active_campaign/client.rb [hunk 2]
```diff
@@ -30,7 +30,7 @@ class Client
     attr_reader :config
 
     def initialize(conf = {})
-      @config = conf
+      @config = Configuration.new.to_h.merge(conf)
```
Comment (maysam) [inline lib/active_campaign/client.rb:33]: for me, it doesn't merge conf at all and I always end up with default configuration
